version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '4000:3000'
    environment:
      - NEXT_PUBLIC_JWT_EXPIRATION=5m
      - NEXT_PUBLIC_JWT_SECRET=dd5f3089-40c3-403d-af14-d0c228b05cb4
      - NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET=7c4c1c50-3230-45bf-9eae-c9b2e401c767
      - NEXT_PUBLIC_SERVER_HOST=192.168.1.16:3000
    networks:
      - downloads_mynetwork
    restart: always
networks:
  downloads_mynetwork:
    external: true
